version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/android-mobile"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directories:
      - "/scripts/docker/android-build-container"
      - "/scripts/docker/mxe-build-container"
    schedule:
      interval: "weekly"
